# Generated by Django 3.2.16 on 2022-10-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_myprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocery',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='myprofile',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='user',
            new_name='owner',
        ),
    ]
